
nextjsOnAws:
  component: "@sls-next/serverless-component@3.6.0" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    cloudfront:
      distributionId: E20LI3HP4WH27M
      defaults:
        forward:
          headers:
            [
              CloudFront-Is-Desktop-Viewer,
              CloudFront-Is-Mobile-Viewer,
              CloudFront-Is-Tablet-Viewer
            ]